spring:
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create
      
  datasource:
    url: jdbc:mysql://localhost:3306/eventfinder?characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: eventfinder.acc@gmail.com
    password: Alma1234
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
logging:
  level:
    org:
      springframework:
        security: DEBUG    
server.contextPath: /eventfinder
